# BEGIN COPYRIGHT BLOCK
# (C) 2018 Red Hat, Inc.
# All rights reserved.
# END COPYRIGHT BLOCK

services:
  - docker

install:
  - docker pull registry.fedoraproject.org/fedora:28
  - docker run
      --name=container
      --detach
      -i
      -v $(pwd):/root/tomcatjss
      registry.fedoraproject.org/fedora:28
  - docker exec container dnf install -y dnf-plugins-core gcc make rpm-build
  - docker exec container dnf copr -y enable @pki/10.6
  - docker exec container dnf builddep -y --spec /root/tomcatjss/tomcatjss.spec.in
  - docker exec container dnf remove -y tomcat-native
  - docker exec container /root/tomcatjss/build.sh --with-timestamp --with-commit-id rpm

script:
  - docker exec container rpm -Uvh /root/build/tomcatjss/RPMS/*
