name: Required Tests

on: [push, pull_request]

jobs:
  init:
    name: Initializing Workflow
    runs-on: ubuntu-latest
    container: fedora:latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Set up test matrix
        id: set-matrix
        run: |
          export latest=$(cat /etc/fedora-release | awk '{ print $3 }')
          export previous=$(cat /etc/fedora-release | awk '{ print $3 - 1 }')
          echo "Running CI against Fedora $previous and $latest"
          if [ "${{ secrets.MATRIX }}" == "" ]
          then
              echo "::set-output name=matrix::{\"os\":[\"$previous\", \"$latest\"]}"
          else
              echo "::set-output name=matrix::${{ secrets.MATRIX }}"
          fi

  build:
    name: Building TomcatJSS
    needs: init
    runs-on: ubuntu-latest
    env:
      COPR_REPO: "@pki/master"
    strategy:
      matrix: ${{ fromJSON(needs.init.outputs.matrix) }}
    container: fedora:${{ matrix.os }}
    steps:
      - name: Install dependencies
        run: |
          dnf install -y dnf-plugins-core gcc make rpm-build git

      - name: Clone repository
        uses: actions/checkout@v2

      - name: Install build dependencies
        run: |
          dnf copr -y enable ${{ env.COPR_REPO }}
          dnf builddep -y --spec tomcatjss.spec
          dnf remove -y tomcat-native

      - name: Build packages
        run: |
          ./build.sh --with-timestamp --with-commit-id --work-dir=../packages rpm

      - name: Install packages
        run: rpm -Uvh ../packages/RPMS/*
